fixed the script name in error message.

diff --git a/pipelines/incubator/image-retag-task.yaml b/pipelines/incubator/image-retag-task.yaml
--- a/pipelines/incubator/image-retag-task.yaml
+++ b/pipelines/incubator/image-retag-task.yaml
@@ -80,7 +80,7 @@ spec:
           retVal=$?
           if [ $retVal -ne 0 ]
           then
-             echo "[ERROR] The script failed(/scripts/application_image_registry_access_setup.sh)" >&2
+             echo "[ERROR] The script failed(/scripts/image_registry_access_setup.sh)" >&2
              exit $retVal
           fi
           
