updated the script name

diff --git a/pipelines/incubator/validate-active-stack-task.yaml b/pipelines/incubator/validate-active-stack-task.yaml
--- a/pipelines/incubator/validate-active-stack-task.yaml
+++ b/pipelines/incubator/validate-active-stack-task.yaml
@@ -96,12 +96,12 @@ spec:
         
         # Configure image registry access in the container by adding it to the insecure registry list or enabling TLS verification
         # by adding it to the trust store based on OpenShift cluster resource configuration.
-        echo "INFO: Running the script /scripts/application_image_registry_access_setup.sh ...."
-        /scripts/application_image_registry_access_setup.sh
+        echo "INFO: Running the script /scripts/image_registry_access_setup.sh ...."
+        /scripts/image_registry_access_setup.sh
         retVal=$?
         if [ $retVal -ne 0 ]
         then
-           echo "ERROR: The script failed(/scripts/application_image_registry_access_setup.sh), and the image registry access setup was not complete, aborting the pipelinerun." >&2
+           echo "ERROR: The script failed(/scripts/image_registry_access_setup.sh), and the image registry access setup was not complete, aborting the pipelinerun." >&2
            exit $retVal
         fi
        
